apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-app
  labels:
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
        version: blue
  template:
    metadata:
      labels:
        version: blue
    spec:
      containers:
      - name: app
        image: zarakmughal/capstone
        ports:
        - containerPort: 80